patterns = [
    (r'\b(?P<RG>\d{2}\.\d{3}\.\d{3}-\d{1})\b', 'RG'),
    (r'\b(?P<CPF>\d{3}\.\d{3}\.\d{3}-\d{2})\b', 'CPF'),
    (r'\b(?P<CNPJ>\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2})\b', 'CNPJ'),
    (r'\b(?P<Telefone>\d{4,5}-\d{4})\b', 'Telefone'),
    (r'\b(?P<Email>[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,})\b', 'Email'),
    (r'\b(?P<Gênero>Masculino|Feminino|Outro)\b', 'Gênero'),
    (r'\b(?P<DataNascimento>\d{2}/\d{2}/19\d{2}|20\d{2})\b', 'Data de nascimento'),
    (r'\b(?P<LocalNascimento>[A-Z][a-z]+\s[A-Z][a-z]+,\s[A-Z][a-z]+)\b', 'Local de nascimento'),
    (r'\b(?P<PlacaAutomóvel>[A-Z]{3}-\d{4})\b', 'Placa de automóvel'),
    (r'\b(?P<OrigemRacial>Branco|Negro|Pardo|Indígena|Amarelo)\b', 'Origem racial ou étnica'),
    (r'\b(?P<ConvicçãoReligiosa>Católica|Evangélica|Ateísta|Agnóstica)\b', 'Convicção religiosa'),
    (r'\b(?P<OpiniãoPolítica>Liberal|Conservador|Socialista|Anarquista)\b', 'Opinião política'),
    (r'\b(?P<DadoSaúde>Vida|Sexual)\b', 'Dado referente à saúde ou à vida sexual'),
    (r'\b(?P<DadoGenéticoBiométrico>Genético|Biométrico)\b', 'Dado genético ou biométrico'),
]
